# Generated by Django 3.0.5 on 2020-05-07 12:27

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email đã tồn tại.'}, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username đã tồn tại.'}, help_text='Bắt buộc. Không quá 150 ký tự. Chỉ bao gồm chữ cái, số và dấu chấm(.).', max_length=150, unique=True, validators=[account.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
